### ISSUE TITLE
Epic Feature: Implement backend logic with sessions

### ISSUE THREAD

**Issue by kyro-D** [kyro-D/SpotifyProjectRepo#8]
Currently application uses `userId` to handle storing access tokens for using the apis. Migrate this logic to be session based. 

- [x] Read session best practices

- [ ] ~~Refactor `userUtils.js` to be session based.~~ Not necessary because library being used has its own storage methods. 

- [x] Refactor `app.js` to retrieve session Id via cookie. 

- [x] Refactor front end to utilize session ids instead of user ids. ~~This will require a react store and the front end refactor will include implementing this store. ~~ library being used has its own store but requires backend store to be used in tandem for production deployment. 

Using `express-session` https://github.com/expressjs/session as session based management middleware. It requires a session store to use for a production deployment. I am opting to use a sql based store so this effort will tie into #9 (if not completely encompass all of the backend db effort).
